<a href="https://colab.research.google.com/github/opopiol/ML_project/blob/model/raport.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **1. EDA**



*   Element listy
*   Element listy



In [ ]:
Data scaling is a recommended pre-processing step when working with many machine learning algorithms.

### **2. Metrics**

In [ ]:
y.value_counts()

y 
 1    3375
-1     375
dtype: int64

The distribution of the labels is very uneven. They appear in proportions of about 1:10.

That’s why we decided to choose f1-score because it fits the best to our dataset and deals best with disproportion. This metric is the harmonic mean of the both precision and recall.

And because we have to predict the class of given data we use classifiers. 

### **3. Baseline**

For the base model we choose `DummyClassifier()`, beacuase it is a simple baseline for the other classifiers. 

Strategies we used are `['stratified', 'most_frequent', 'constant', 'uniform']` and we get the following results:


> `For stratified strategy f1 score is 0.8951813214108296 with labels: [-1  1]
[[ 14  98]
 [111 902]]


For most_frequent strategy f1 score is 0.9476145930776426 with labels: [1]
[[   0  112]
 [   0 1013]]
For prior strategy f1 score is 0.9476145930776426 with labels: [1]
[[   0  112]
 [   0 1013]]
For uniform strategy f1 score is 0.6650093225605965 with labels: [-1  1]
[[ 60  52]
 [491 522]]`

The highest results were achived by `most_frequent` strategy and `prior` strategy with a result above 94%. But both of them were only using one, majority class.

For another baseline, we decided to check also `DecisionTreeClassifier()` and its f1 scora was above 96%.

### **4. Model**

In the first approach to choosing the best class factor we decided to check the following three classifiers `LogisticRegression(random_state=0, max_iter = 1000)`, `KNeighborsClassifier()` and `SVC()`.

Their f1 scores were:

*   `LogisticRegression` 0.891662506240639
*   `KNeighborsClassifier` 0.9803921568627452
*   `SVC` 0.9767211490837047

Because `LogisticRegression` achieved a result lower than the base, it was not taken into account further.

`KNeighborsClassifier`, with its default number of 5 neighbors, performed the best out of three given classifiers. Also model is usually robust to noisy data.

`SVC` also performed better f1 score than our base model. 


Later we were looking for more advanced calssifiers. Some of the most popular are AdaBoost, Gradient Boosting, and XGBoost. Due to the long processing time, we decided to try only one- `AdaBoostClassifier()` to see what results it would achieve. In its basic model, without the given parameters, it achieved a f1 score 0.9656188605108056, so above baseline score.

> In its basic model, without the given parameters, it achieved a f1 score 0.9656188605108056, so above baseline score.

Then a pipeline was created to see which parameters of `AdaBoostClassifier()` performed best. In the pipeline were used: `'n_estimators': [50, 100, 150], 'learning_rate': [0.1, 0.01, 0.05]`. It was done in order not to overload the fan pipeline so much. 

> It turns out that the best parameters was `algorithm='SAMME.R', base_estimator=None, learning_rate=0.05, n_estimators=50, random_state=None`. The model achieved a score of 0.9793510324483775.

These params were used in final pipeline with others classifiers.

The final pipeline had parameters and models choosen earlier.

`PCA()` got n_components = 0.99, because with this params it performed the best in EDA's clustering.
As scaler we got `StandardScaler()` same as in EDA.

In pipeline three calssifier were checked: 

*   `SVC()` with `kernel: ['linear', 'poly'], class_weight: ['balanced'], and C: np.logspace(1,4,5)`
*   `KNeighborsClassifier()` with `n_neighbors': [2, 4, 6, 8, 10], algorithm': ['auto']`
*   `AdaBoostClassifier()` with the parameters that came out in the previous pipeline `n_estimators': [50], learning_rate': [0.1]`






